# Generated by Django 4.2.4 on 2023-09-04 20:38

from django.db import migrations, models
import employers.models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name="Employer's email"),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name="Employer's name"),
        ),
        migrations.AlterField(
            model_name='employer',
            name='verification_code',
            field=models.CharField(default=employers.models.verify_code, max_length=25, unique=True),
        ),
    ]
