# Generated by Django 4.2.4 on 2023-09-04 19:03

from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.TextField(default=secrets.token_urlsafe, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Job title')),
                ('job_type', models.CharField(choices=[('Open', 'Open'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('NSS Internship', 'NSS Internship')], default='Open', max_length=15, verbose_name='Job type')),
                ('description', models.TextField(verbose_name='Job description')),
                ('company', models.CharField(max_length=255, verbose_name='Company name')),
                ('location', models.CharField(max_length=255, verbose_name='Job location')),
                ('salary', models.CharField(default='Not stated', max_length=50, verbose_name='Salary')),
                ('requirements', models.TextField(default='Not applicable', verbose_name='Qualification & Experience')),
                ('application_method', models.CharField(max_length=255, verbose_name='How to apply')),
                ('closing_date', models.DateField(verbose_name='Closing date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_category', to='category.category', to_field='title')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
